name: Test
on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  macOS:
    name: Test macOS
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install xcaudit
        uses: Alexander-Ignition/XCAudit@main
      - name: Build and test
        run: |
          NSUnbufferedIO=YES swift test --enable-code-coverage --disable-automatic-resolution 2>&1 | xcaudit
          ./.github/scripts/codecov.sh $(swift test --show-codecov-path) >> $GITHUB_STEP_SUMMARY
        shell: bash
  Linux:
    name: Test Linux
    runs-on: ubuntu-latest
    container:
      image: swift:5.6-focal
    steps:
      - uses: actions/checkout@v3
      - run: swift test
