name: Test
on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Run tests
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install xcaudit
        uses: Alexander-Ignition/XCAudit@main
      - name: Build and test
        run: |
          swift test --enable-code-coverage --disable-automatic-resolution 2>&1 | xcaudit
          ./.github/scripts/codecov.sh $(swift test --show-codecov-path) >> $GITHUB_STEP_SUMMARY
        shell: bash
